-version: 2.0

# Job definitions
# ===============
jobs:
  build-and-publish-beta:
    docker:
      - image: "alpine:3.10.3"
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: |
            apk update
            apk add --no-cache curl jq yarn zip
            yarn install --force
      - run:
          name: "Build and ZIP Extension for BETA"
          command: |
            yarn build-dev

  build-and-publish-prod:
    docker:
      - image: "alpine:3.10.3"
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: |
            apk update
            apk add --no-cache curl jq yarn zip
            yarn install --force
      - run:
          name: "Build and ZIP Extension for PRODUCTION"
          command: |
            yarn build
      - store_artifacts:
          name: "Storing Artifact"
          path: ./minimal-consent-prod.zip
      - run:
          name: "Publish to the Google Chrome Store -- Production"
          command: |
            echo "Publishing Extension -- Production"
            ACCESS_TOKEN=$(curl "https://accounts.google.com/o/oauth2/token" -d "client_id=${CLIENT_ID}&client_secret=${CLIENT_SECRET}&refresh_token=${REFRESH_TOKEN}&grant_type=refresh_token&redirect_uri=urn:ietf:wg:oauth:2.0:oob" | jq -r .access_token)
            UPLOAD_RESULT=$(curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -X PUT -T ./minimal-consent-prod.zip -v "https://www.googleapis.com/upload/chromewebstore/v1.1/items/${APP_ID_PRODUCTION}")
            echo $UPLOAD_RESULT && echo $UPLOAD_RESULT | grep -vi error
            curl -f -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -H "Content-Length: 0" -X POST -v "https://www.googleapis.com/chromewebstore/v1.1/items/${APP_ID_PRODUCTION}/publish"


# Workflow definitions
# ====================
workflows:
  version: 2

  build_and_publish_beta:
    jobs:
      - build-and-publish-beta: {requires: [test]}

  build_and_publish_prod:
    jobs:
      - build-and-publish-prod: {requires: [test]}
