version: 2.0

# Job definitions
# ===============
jobs:
  test:
    docker:
      - image: "alpine:3.10.3"
    steps:
      - checkout
      - run:
          name: "Install Test Dependencies"
          command: |
            apk add --no-cache yarn
            yarn
      - run:
          name: "Run Tests"
          command: yarn test

  build-and-publish-beta:
    docker:
      - image: "alpine:3.10.3"
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: |
            apk update
            apk add --no-cache curl jq yarn zip
            yarn install --force
      - run:
          name: "Build Extension for BETA"
          command: |
            yarn build-dev
      - run:
          name: "Package Extension for BETA"
          command: |
            zip -r ./minimal_consent_beta.zip dist
      - store_artifacts:
          name: "Storing Artifact"
          path: ./minimal_consent_beta.zip
      - run:
          name: "Publish to the Google Chrome Store - BETA Channel"
          command: |
            echo "Publishing Extension -- Beta Channel"
            ACCESS_TOKEN=$(curl "https://accounts.google.com/o/oauth2/token" -d "client_id=${CLIENT_ID}&client_secret=${CLIENT_SECRET}&refresh_token=${REFRESH_TOKEN}&grant_type=refresh_token&redirect_uri=urn:ietf:wg:oauth:2.0:oob" | jq -r .access_token)
            UPLOAD_RESULT=$(curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -X PUT -T ./minimal_consent_beta.zip -v "https://www.googleapis.com/upload/chromewebstore/v1.1/items/${APP_ID_STAGING}")
            echo $UPLOAD_RESULT && echo $UPLOAD_RESULT | grep -vi error
            curl -f -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -H "Content-Length: 0" -X POST -v "https://www.googleapis.com/chromewebstore/v1.1/items/${APP_ID_STAGING}/publish"

  build-and-publish-prod:
    docker:
      - image: "alpine:3.10.3"
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: |
            apk update
            apk add --no-cache curl jq yarn zip
            yarn install --force
      - run:
          name: "Build Extension for PRODUCTION"
          command: |
            yarn build
      - run:
          name: "Package Extension for PRODUCTION"
          command: |
            zip -r minimal_consent_prod.zip dist
      - store_artifacts:
          name: "Storing Artifact"
          path: ./minimal_consent_prod.zip
      - run:
          name: "Publish to the Google Chrome Store -- Production"
          command: |
            echo "Publishing Extension -- Production"
            ACCESS_TOKEN=$(curl "https://accounts.google.com/o/oauth2/token" -d "client_id=${CLIENT_ID}&client_secret=${CLIENT_SECRET}&refresh_token=${REFRESH_TOKEN}&grant_type=refresh_token&redirect_uri=urn:ietf:wg:oauth:2.0:oob" | jq -r .access_token)
            UPLOAD_RESULT=$(curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -X PUT -T /root/workspace/minimal_consent_prod.zip -v "https://www.googleapis.com/upload/chromewebstore/v1.1/items/${APP_ID_PRODUCTION}")
            echo $UPLOAD_RESULT && echo $UPLOAD_RESULT | grep -vi error
            curl -f -H "Authorization: Bearer ${ACCESS_TOKEN}" -H "x-goog-api-version: 2" -H "Content-Length: 0" -X POST -v "https://www.googleapis.com/chromewebstore/v1.1/items/${APP_ID_PRODUCTION}/publish"


# Workflow definitions
# ====================
workflows:
  version: 2

  build_and_test:
    jobs:
      - test: {filters: {branches: {ignore: [production, staging]}}}

  build_and_publish_beta:
    jobs:
      - test: {filters: {branches: {only: [dev]}}}
      - build-and-publish-beta: {requires: [test]}

  build_and_publish_prod:
    jobs:
      - test: {filters: {branches: {only: [master]}}}
      - build-and-publish-prod: {requires: [test]}
